version: '3'
services:
  application:
    image: javaee-jcache-redisson
    build: .
    ports:
      - "8080:8080"
    links:
      - redis:redis-host
    depends_on:
      - redis

  redis:
    image: redis